import Foundation

/// Ordered, provider-neutral content carried by a chat message or prompt section.
public struct MessageContent: Sendable, Codable, Equatable {
    /// The ordered content parts.
    public let parts: [MessageContentPart]

    /// Creates ordered message content from the supplied parts.
    public init(parts: [MessageContentPart]) {
        self.parts = parts
    }

    /// Creates text-only message content.
    public init(_ text: String) {
        parts = [.text(text)]
    }

    /// The concatenated text projection used by legacy text-only interfaces.
    ///
    /// - Complexity: O(n), where n is the total number of text characters.
    public var text: String {
        parts.compactMap(\.text).joined()
    }

    /// Whether the content contains no binary media parts.
    public var isTextOnly: Bool {
        parts.allSatisfy { if case .text = $0 { return true }; return false }
    }

    /// Whether preserving this value requires the additive `contentParts` Codable field.
    public var requiresContentPartsEncoding: Bool {
        parts != [.text(text)]
    }

    /// The conservative prompt-token estimate for the content.
    public var estimatedTokens: Int {
        parts.reduce(into: 0) { result, part in
            switch part {
            case let .text(text):
                result += max(1, text.count / 4)
            case let .image(image):
                result += image.estimatedTokens ?? ImageContent.defaultTokenEstimate
            case let .audio(audio):
                result += audio.estimatedTokens ?? AudioContent.defaultTokenEstimate
            }
        }
    }
}

/// One ordered part of provider-neutral message content.
public enum MessageContentPart: Sendable, Codable, Equatable {
    /// Plain text.
    case text(String)
    /// Encoded image input.
    case image(ImageContent)
    /// Encoded audio input or output.
    case audio(AudioContent)

    /// The text value when this is a text part.
    public var text: String? {
        guard case let .text(value) = self else { return nil }
        return value
    }
}

/// A hint controlling how much image detail a model should inspect.
public enum ImageDetail: String, Sendable, Codable, Equatable {
    case automatic
    case low
    case high
}

/// Encoded image content supplied by a caller.
public struct ImageContent: Sendable, Codable, Equatable {
    /// Conservative prompt-budget fallback used when the caller supplies no estimate.
    public static let defaultTokenEstimate = 1_024

    public let data: Data
    public let mediaType: String
    public let detail: ImageDetail?
    public let estimatedTokens: Int?

    /// Creates encoded image content without performing file or network I/O.
    public init(
        data: Data,
        mediaType: String,
        detail: ImageDetail? = nil,
        estimatedTokens: Int? = nil
    ) {
        self.data = data
        self.mediaType = mediaType
        self.detail = detail
        self.estimatedTokens = estimatedTokens
    }
}

/// A provider-neutral encoded audio format.
public enum AudioFormat: String, Sendable, Codable, Equatable, CaseIterable {
    case wav
    case mp3
    case flac
    case opus
    case aac
    case pcm16

    /// The conventional MIME type for the format.
    public var mediaType: String {
        switch self {
        case .wav: "audio/wav"
        case .mp3: "audio/mpeg"
        case .flac: "audio/flac"
        case .opus: "audio/opus"
        case .aac: "audio/aac"
        case .pcm16: "audio/L16"
        }
    }
}

/// A temporary provider-side reference that can preserve recent generated audio in history.
public struct AudioContinuationReference: Sendable, Codable, Equatable {
    public let provider: LLMProvider
    public let id: String
    public let expiresAt: Date

    public init(provider: LLMProvider, id: String, expiresAt: Date) {
        self.provider = provider
        self.id = id
        self.expiresAt = expiresAt
    }

    /// Returns whether the reference is usable at the supplied time.
    public func isValid(at date: Date = Date()) -> Bool {
        date < expiresAt
    }
}

/// Encoded audio content supplied by a caller or generated by a model.
public struct AudioContent: Sendable, Codable, Equatable {
    /// Conservative prompt-budget fallback used when the caller supplies no estimate.
    public static let defaultTokenEstimate = 2_048

    public let data: Data
    public let format: AudioFormat
    public let transcript: String?
    public let estimatedTokens: Int?
    public let continuation: AudioContinuationReference?

    /// Creates encoded audio content without performing file or network I/O.
    public init(
        data: Data,
        format: AudioFormat,
        transcript: String? = nil,
        estimatedTokens: Int? = nil,
        continuation: AudioContinuationReference? = nil
    ) {
        self.data = data
        self.format = format
        self.transcript = transcript
        self.estimatedTokens = estimatedTokens
        self.continuation = continuation
    }
}

/// A media capability explicitly enabled for a configured model.
public enum ModelCapability: String, Sendable, Codable, Hashable, CaseIterable {
    case imageInput
    case audioInput
    case audioOutput
}

/// A response modality requested for a chat turn.
public enum ResponseModality: String, Sendable, Codable, Equatable, Hashable {
    case text
    case audio
}

/// Provider-neutral options required when requesting generated audio.
public struct AudioOutputOptions: Sendable, Codable, Equatable {
    public let format: AudioFormat
    public let voice: String

    public init(format: AudioFormat, voice: String) {
        self.format = format
        self.voice = voice
    }
}

/// One decoded generated-audio fragment from a provider stream.
public struct LLMAudioDelta: Sendable, Codable, Equatable {
    public let data: Data
    public let format: AudioFormat
    public let transcript: String?
    public let continuation: AudioContinuationReference?

    public init(
        data: Data,
        format: AudioFormat,
        transcript: String? = nil,
        continuation: AudioContinuationReference? = nil
    ) {
        self.data = data
        self.format = format
        self.transcript = transcript
        self.continuation = continuation
    }
}

/// Errors raised when multimodal content cannot be represented safely.
public enum MultimodalContentError: PKError, Sendable, Equatable {
    case emptyMedia
    case invalidImageMediaType(String)
    case missingCapability(ModelCapability)
    case missingAudioOutputOptions
    case audioOptionsWithoutAudioModality
    case unsupportedAudioFormat(AudioFormat, provider: LLMProvider)
    case unsupportedAudioVoice(String, provider: LLMProvider)
    case unsupportedContentLayout(provider: LLMProvider)
    case inconsistentAudioFormat(expected: AudioFormat, actual: AudioFormat)
    case missingAudioTranscript

    public var errorDomain: String { PKErrorDomain.llm }

    public var errorCode: Int {
        switch self {
        case .emptyMedia: 7601
        case .invalidImageMediaType: 7602
        case .missingCapability: 7603
        case .missingAudioOutputOptions: 7604
        case .audioOptionsWithoutAudioModality: 7605
        case .unsupportedAudioFormat: 7606
        case .unsupportedAudioVoice: 7607
        case .unsupportedContentLayout: 7608
        case .inconsistentAudioFormat: 7609
        case .missingAudioTranscript: 7610
        }
    }

    public var userFriendlyMessage: String {
        switch self {
        case .emptyMedia: "Image and audio content must contain data."
        case let .invalidImageMediaType(mediaType): "The image MIME type '\(mediaType)' is invalid."
        case let .missingCapability(capability): "The configured model does not support \(capability.rawValue)."
        case .missingAudioOutputOptions: "Audio output requires a voice and output format."
        case .audioOptionsWithoutAudioModality: "Audio output options require the audio response modality."
        case let .unsupportedAudioFormat(format, provider): "\(provider.rawValue) cannot preserve the requested \(format.rawValue) audio format."
        case let .unsupportedAudioVoice(voice, provider): "\(provider.rawValue) does not support the requested audio voice '\(voice)'."
        case let .unsupportedContentLayout(provider): "\(provider.rawValue) cannot preserve the requested multimodal content order."
        case let .inconsistentAudioFormat(expected, actual): "The audio stream changed format from \(expected.rawValue) to \(actual.rawValue)."
        case .missingAudioTranscript: "The provider completed audio output without the transcript required for thread history."
        }
    }
}

public extension MessageContent {
    /// Validates that every media part contains bytes.
    func validateMedia() throws {
        for part in parts {
            switch part {
            case let .image(image) where image.data.isEmpty:
                throw MultimodalContentError.emptyMedia
            case let .audio(audio) where audio.data.isEmpty:
                throw MultimodalContentError.emptyMedia
            case let .image(image) where !image.mediaType.lowercased().hasPrefix("image/"):
                throw MultimodalContentError.invalidImageMediaType(image.mediaType)
            default:
                break
            }
        }
    }
}
