import Foundation
import struct JSONSchema.Schema
import Synchronization

/// Provider-neutral description of a tool the LLM may call, sent alongside a chat request.
public struct LLMToolDefinition: Sendable, Codable {
    /// The tool's callable identifier, as the model will reference it in a tool call.
    public let name: String
    /// Human-readable description shown to the model to guide when/how to call the tool.
    public let description: String?
    /// JSON Schema describing the tool's call arguments.
    public let parameters: Schema?
    /// Whether the provider should enforce strict schema adherence, where supported.
    public let strict: Bool?

    public init(
        name: String,
        description: String? = nil,
        parameters: Schema? = nil,
        strict: Bool? = nil
    ) {
        self.name = name
        self.description = description
        self.parameters = parameters
        self.strict = strict
    }
}

/// Controls whether/which tool the model is required to call for a given request.
public enum LLMToolChoice: Sendable, Codable, Equatable {
    /// Let the model decide whether to call a tool.
    case auto
    /// Force the model to call the named tool.
    case function(String)
}

/// The shape the model's response content must take.
public enum LLMResponseFormat: Sendable, Codable, Equatable {
    /// Plain text response.
    case text
    /// Response constrained to be a JSON object, without a specific schema.
    case jsonObject
    /// Response constrained to conform to the given named JSON Schema.
    case jsonSchema(LLMResponseSchema)

    public static func == (lhs: LLMResponseFormat, rhs: LLMResponseFormat) -> Bool {
        switch (lhs, rhs) {
        case (.text, .text), (.jsonObject, .jsonObject):
            return true
        case let (.jsonSchema(lhsSchema), .jsonSchema(rhsSchema)):
            return lhsSchema == rhsSchema
        default:
            return false
        }
    }
}

/// Named JSON Schema used to constrain a structured-output response.
public struct LLMResponseSchema: Sendable, Codable, Equatable {
    /// The schema's name, as required by structured-output APIs that key on it.
    public let name: String
    /// Human-readable description of what the schema represents.
    public let description: String?
    /// The JSON Schema itself.
    public let schema: Schema?
    /// Whether the provider should enforce strict schema adherence, where supported.
    public let strict: Bool?

    public init(
        name: String,
        description: String? = nil,
        schema: Schema? = nil,
        strict: Bool? = nil
    ) {
        self.name = name
        self.description = description
        self.schema = schema
        self.strict = strict
    }

    public static func == (lhs: LLMResponseSchema, rhs: LLMResponseSchema) -> Bool {
        lhs.name == rhs.name &&
            lhs.description == rhs.description &&
            lhs.strict == rhs.strict &&
            encodeSchema(lhs.schema) == encodeSchema(rhs.schema)
    }
}

/// A completed tool call as reported by the model in a non-streaming response.
public struct LLMToolCall: Sendable, Codable, Equatable {
    /// Provider-assigned identifier for this call, used to correlate the tool's result
    /// back to the request.
    public let id: String
    /// The name of the tool being called.
    public let name: String
    /// The call arguments, as a raw JSON string (not yet decoded/validated).
    public let arguments: String

    public init(id: String, name: String, arguments: String) {
        self.id = id
        self.name = name
        self.arguments = arguments
    }
}

/// Provider-neutral chat message sent to/received from an `LLMClientProtocol` conformer.
public struct LLMMessage: Sendable, Codable, Equatable {
    /// The message's speaker role in the conversation.
    public enum Role: String, Sendable, Codable {
        /// System-level instructions.
        case system
        /// A message from the end user.
        case user
        /// A message generated by the model.
        case assistant
        /// A tool's execution result, correlated to a prior assistant tool call.
        case tool
        /// Developer-authored instructions, for providers that distinguish this from `.system`.
        case developer
    }

    /// The message's speaker role.
    public let role: Role
    /// The message's text content.
    public let content: String
    /// Optional name qualifying the sender (e.g. a tool's name for `.tool` messages).
    public let name: String?
    /// For `.tool` messages, the id of the tool call this message is the result of.
    public let toolCallID: String?
    /// For `.assistant` messages, any tool calls the model made.
    public let toolCalls: [LLMToolCall]?

    /// Structured reasoning/thinking to echo back on follow-up turns for reasoning models that
    /// require it (STAB-8). Threaded from persisted `Message.reasoning` by the history-reconstruction
    /// path (`RenderedPrompt.buildMessages()` / `buildAssistantMessage`). The field name is
    /// provider-neutral; each provider adapter maps it onto its own wire field:
    /// Ollama → `thinking`, OpenRouter → `reasoning`. The OpenAI Chat Completions adapter
    /// intentionally omits it (the Chat Completions API has no reasoning-echo message field;
    /// reasoning continuation there uses the Responses API / `previous_response_id`, which is
    /// out of scope). `nil` for non-reasoning flows — existing messages are byte-identical.
    public let reasoning: String?

    public init(
        role: Role,
        content: String,
        name: String? = nil,
        toolCallID: String? = nil,
        toolCalls: [LLMToolCall]? = nil,
        reasoning: String? = nil
    ) {
        self.role = role
        self.content = content
        self.name = name
        self.toolCallID = toolCallID
        self.toolCalls = toolCalls
        self.reasoning = reasoning
    }
}

/// Breakdown of prompt-token accounting, e.g. how many prompt tokens were served from
/// a provider-side prompt cache.
public struct LLMTokenUsagePromptDetails: Sendable, Codable, Equatable {
    /// Number of prompt tokens served from cache, where the provider reports it.
    public let cachedTokens: Int?

    enum CodingKeys: String, CodingKey {
        case cachedTokens = "cached_tokens"
    }

    public init(cachedTokens: Int? = nil) {
        self.cachedTokens = cachedTokens
    }
}

/// Token accounting for a completed (or in-progress streamed) LLM response.
public struct LLMTokenUsage: Sendable, Codable, Equatable {
    /// Number of tokens in the prompt/input.
    public let promptTokens: Int?
    /// Number of tokens generated in the response.
    public let completionTokens: Int?
    /// Total tokens (prompt + completion) counted for this request.
    public let totalTokens: Int?
    /// Additional breakdown of prompt-token accounting (e.g. cache hits), where the provider reports it.
    public let promptTokensDetails: LLMTokenUsagePromptDetails?

    /// Shared streaming usage metadata stays snake_case-safe here so providers can decode
    /// directly into the transport-neutral contract without relying on decoder-wide conversion.
    enum CodingKeys: String, CodingKey {
        case promptTokens = "prompt_tokens"
        case completionTokens = "completion_tokens"
        case totalTokens = "total_tokens"
        case promptTokensDetails = "prompt_tokens_details"
    }

    public init(
        promptTokens: Int? = nil,
        completionTokens: Int? = nil,
        totalTokens: Int? = nil,
        promptTokensDetails: LLMTokenUsagePromptDetails? = nil
    ) {
        self.promptTokens = promptTokens
        self.completionTokens = completionTokens
        self.totalTokens = totalTokens
        self.promptTokensDetails = promptTokensDetails
    }
}

/// Incremental function-call fields within a streamed tool-call delta; provider streams
/// send the tool call's name/arguments piecemeal across multiple chunks.
public struct LLMToolCallDeltaFunction: Sendable, Codable, Equatable {
    /// The tool name fragment/value for this delta, if present in this chunk.
    public let name: String?
    /// The arguments-string fragment for this delta, to be concatenated across chunks.
    public let arguments: String?

    public init(name: String? = nil, arguments: String? = nil) {
        self.name = name
        self.arguments = arguments
    }
}

/// One incremental tool-call fragment within a streamed response chunk.
public struct LLMToolCallDelta: Sendable, Codable, Equatable {
    /// Position of this tool call among the (possibly multiple) parallel calls being streamed.
    public let index: Int?
    /// The tool call's id, present on the chunk that starts the call.
    public let id: String?
    /// The incremental function name/arguments fragment carried by this chunk.
    public let function: LLMToolCallDeltaFunction?

    public init(index: Int? = nil, id: String? = nil, function: LLMToolCallDeltaFunction? = nil) {
        self.index = index
        self.id = id
        self.function = function
    }
}

/// One incremental content/role fragment within a streamed response chunk.
public struct LLMStreamDelta: Sendable, Codable, Equatable {
    /// The message role, present on the chunk that starts the message.
    public let role: LLMMessage.Role?
    /// Incremental text content fragment for this chunk.
    public let content: String?
    /// Structured reasoning/thinking delta emitted as a distinct field by some providers
    /// (e.g. OpenRouter `delta.reasoning`, OpenAI reasoning models' `reasoning`/`reasoning_content`,
    /// Ollama thinking models' `thinking`). Routed directly into `TurnOutputs.appendThinking` by
    /// `LLMStreamingStage`. `nil` for non-reasoning models — existing flows are byte-identical.
    /// The `<think>...</think>` tag-scraping path in `StreamingParser` remains the fallback for
    /// models that emit inline reasoning text inside `content`.
    public let reasoning: String?

    public let toolCalls: [LLMToolCallDelta]?

    /// `tool_calls` is part of the shared streaming contract, so it is spelled out explicitly
    /// instead of depending on a decoder-wide snake_case conversion.
    enum CodingKeys: String, CodingKey {
        case role
        case content
        case reasoning
        case toolCalls = "tool_calls"
    }

    public init(
        role: LLMMessage.Role? = nil,
        content: String? = nil,
        reasoning: String? = nil,
        toolCalls: [LLMToolCallDelta]? = nil
    ) {
        self.role = role
        self.content = content
        self.reasoning = reasoning
        self.toolCalls = toolCalls
    }
}

/// One choice within a streamed response chunk (providers may stream multiple parallel
/// completions per request, indexed by `index`).
public struct LLMStreamChoice: Sendable, Codable, Equatable {
    /// Index of this choice among the response's parallel completions.
    public let index: Int
    /// The incremental content for this choice in this chunk.
    public let delta: LLMStreamDelta
    /// Why generation stopped, present on the final chunk for this choice.
    public let finishReason: String?

    /// `finish_reason` is part of the streaming wire contract and must survive decode intact.
    enum CodingKeys: String, CodingKey {
        case index
        case delta
        case finishReason = "finish_reason"
    }

    public init(index: Int, delta: LLMStreamDelta, finishReason: String? = nil) {
        self.index = index
        self.delta = delta
        self.finishReason = finishReason
    }
}

/// One provider-neutral streamed response chunk from `LLMClientProtocol.chatStream`.
public struct LLMStreamChunk: Sendable, Codable, Equatable {
    /// Provider-assigned identifier for the overall response this chunk belongs to.
    public let id: String
    /// The model that generated the response.
    public let model: String
    /// The choice(s) carried by this chunk.
    public let choices: [LLMStreamChoice]
    /// Token usage accounting, typically only populated on the final chunk.
    public let usage: LLMTokenUsage?

    public init(id: String, model: String, choices: [LLMStreamChoice], usage: LLMTokenUsage? = nil) {
        self.id = id
        self.model = model
        self.choices = choices
        self.usage = usage
    }
}

/// A configuration endpoint URL broken into the components a provider client's HTTP
/// transport configuration needs individually.
public struct EndpointComponents: Sendable, Equatable {
    /// The endpoint's hostname.
    public let host: String
    /// The endpoint's port.
    public let port: Int
    /// The endpoint's URL scheme (e.g. `"https"`).
    public let scheme: String

    public init(host: String, port: Int, scheme: String) {
        self.host = host
        self.port = port
        self.scheme = scheme
    }
}

/// A concrete provider SDK adapter (OpenAI, Anthropic, Ollama, OpenRouter, ...) that
/// speaks the provider-neutral `LLMMessage`/`LLMStreamChunk` contract. Implementations
/// are registered per `LLMProvider` via `ExternalLLMProviderRegistry`.
public protocol LLMClientProtocol: Sendable {
    /// Streams a chat completion for the given messages/tools/parameters.
    func chatStream(
        messages: [LLMMessage],
        tools: [LLMToolDefinition]?,
        toolChoice: LLMToolChoice?,
        responseFormat: LLMResponseFormat?,
        generationParameters: GenerationParameters?
    ) async -> AsyncThrowingStream<LLMStreamChunk, Error>

    /// Sends a single non-streamed message and returns the full text response.
    func sendMessage(
        _ content: String,
        responseFormat: LLMResponseFormat?,
        generationParameters: GenerationParameters?
    ) async throws -> String

    /// Fetches the list of model names available from this provider/endpoint, if the
    /// provider supports discovery. Returns `nil` when unsupported (see default below).
    func fetchAvailableModels() async throws -> [String]?
}

public extension LLMClientProtocol {
    func fetchAvailableModels() async throws -> [String]? {
        nil
    }
}

/// Labeled request payload for constructing a provider client via
/// ``ExternalLLMProviderRegistry/Factory``.
///
/// Replaces the former unlabeled 5-tuple
/// `(LLMConfiguration, EndpointComponents, TimeInterval, Int, String?)` — Swift closure type
/// aliases can't carry argument labels, so `TimeInterval`, `Int`, and `String?` were
/// unidentifiable at any call site. The struct makes every field self-documenting.
public struct ProviderFactoryRequest: Sendable {
    /// The resolved LLM configuration (active provider's settings live at
    /// `config.providers[config.activeProvider]`).
    public let config: LLMConfiguration
    /// Parsed host/port/scheme of `config.endpoint`.
    public let components: EndpointComponents
    /// Per-request HTTP timeout interval.
    public let timeout: TimeInterval
    /// Per-request retry count.
    public let retries: Int
    /// Optional model-name override; `nil` means use `config.modelName` (or the tier-specific
    /// model for utility/fast client construction).
    public let model: String?

    public init(
        config: LLMConfiguration,
        components: EndpointComponents,
        timeout: TimeInterval,
        retries: Int,
        model: String? = nil
    ) {
        self.config = config
        self.components = components
        self.timeout = timeout
        self.retries = retries
        self.model = model
    }
}

/// Process-wide registry mapping `LLMProvider` to a factory that constructs its
/// `LLMClientProtocol` adapter. Provider SDK adapter modules (`PKOpenAIProvider`, etc.)
/// register themselves here at startup so `PositronicKit` can construct clients without
/// depending on any concrete provider module.
public enum ExternalLLMProviderRegistry {
    /// Constructs a provider client from a labeled ``ProviderFactoryRequest``.
    public typealias Factory = @Sendable (ProviderFactoryRequest) -> (any LLMClientProtocol)?

    private static let factories = Mutex<[LLMProvider: Factory]>([:])

    /// Registers or replaces the factory for a provider.
    ///
    /// Re-registration is allowed and simply overwrites the existing factory for that provider.
    /// Provider modules rely on this behavior so hosts can call `register()` defensively at startup.
    public static func register(factory: @escaping Factory, for provider: LLMProvider) {
        factories.withLock {
            $0[provider] = factory
        }
    }

    /// Returns the registered factory for `provider`, if any has been registered.
    public static func factory(for provider: LLMProvider) -> Factory? {
        factories.withLock {
            $0[provider]
        }
    }
}

public func makeEmptyObjectSchema() -> Schema {
    if let schema = try? Schema(instance: #"{"type":"object","properties":{}}"#) {
        return schema
    }
    return ToolParameterSchema.object {}.schemaDefinition
}

private func encodeSchema(_ schema: Schema?) -> String? {
    guard let schema, let data = try? JSONEncoder().encode(schema) else { return nil }
    return String(decoding: data, as: UTF8.self)
}
