#!/usr/bin/env python3
"""Generate versioned documentation landings and navigation from docs/catalog.json."""

from __future__ import annotations

import argparse
import html
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = ROOT / "docs/catalog.json"


def load_catalog() -> dict:
    return json.loads(CATALOG_PATH.read_text(encoding="utf-8"))


def tagged_url(repository: str, ref: str, path: str) -> str:
    is_directory = path.endswith("/")
    path = path.rstrip("/")
    if not path:
        return f"https://github.com/{repository}/tree/{ref}"
    kind = "tree" if is_directory else "blob"
    return f"https://github.com/{repository}/{kind}/{ref}/{path}"


def channel_guides(catalog: dict, channel: str) -> list[dict]:
    return catalog["stable"]["guides"] if channel == "stable" else catalog["guides"]


def landing(catalog: dict, *, channel: str, switch_href: str) -> str:
    repository = catalog["repository"]
    stable = catalog["stable"]
    is_stable = channel == "stable"
    ref = stable["ref"] if is_stable else catalog["next"]["ref"]
    label = f"Stable {stable['version']}" if is_stable else catalog["next"]["label"]
    install = (
        f'.package(url: "https://github.com/{repository}.git", from: "{stable["version"]}")'
        if is_stable
        else f'.package(url: "https://github.com/{repository}.git", branch: "{ref}")'
    )
    cards = "\n".join(
        "      <a class=\"card\" href=\"{}\"><strong>{}</strong><span>{}</span></a>".format(
            html.escape(tagged_url(repository, ref, guide["path"]), quote=True),
            html.escape(guide["title"]),
            html.escape(guide["summary"]),
        )
        for guide in channel_guides(catalog, channel)
    )
    switch_label = catalog["next"]["label"] if is_stable else f"Stable {stable['version']}"
    warning = (
        "This is the immutable tagged release and the default documentation channel."
        if is_stable
        else f"This channel follows main and documents the unreleased {catalog['next']['label']} API. It may change before the next major release."
    )
    return f"""<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <title>PositronicKit — {html.escape(label)}</title>
  <style>
    :root {{ color-scheme: light dark; font-family: system-ui, sans-serif; line-height: 1.5; }}
    body {{ max-width: 64rem; margin: 0 auto; padding: 3rem 1.25rem; }}
    header {{ border-bottom: 1px solid #8886; padding-bottom: 2rem; }}
    .channel {{ display: inline-block; border: 1px solid #8888; border-radius: 999px; padding: .25rem .7rem; }}
    pre {{ overflow: auto; padding: 1rem; border-radius: .6rem; background: #7772; }}
    .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(17rem, 1fr)); gap: .8rem; }}
    .card {{ color: inherit; text-decoration: none; border: 1px solid #8886; border-radius: .7rem; padding: 1rem; }}
    .card span {{ display: block; margin-top: .35rem; opacity: .75; }}
    nav {{ margin-top: 1rem; }}
  </style>
</head>
<body>
  <header>
    <span class=\"channel\">{html.escape(label)}</span>
    <h1>PositronicKit documentation</h1>
    <p>{html.escape(warning)}</p>
    <nav><a href=\"{switch_href}\">Switch to {html.escape(switch_label)}</a> · <a href=\"https://github.com/{repository}\">Repository</a></nav>
  </header>
  <h2>Package dependency</h2>
  <pre><code>{html.escape(install)}</code></pre>
  <h2>Guides</h2>
  <div class=\"grid\">
{cards}
  </div>
</body>
</html>
"""


def llms(catalog: dict) -> str:
    repository = catalog["repository"]
    stable = catalog["stable"]
    lines = [
        "# PositronicKit documentation",
        "",
        f"> Stable {stable['version']} is the default, immutable channel. {catalog['next']['label']} follows main and is unreleased.",
        "",
        "## Stable",
        "",
    ]
    for guide in channel_guides(catalog, "stable"):
        lines.append(f"- [{guide['title']}]({tagged_url(repository, stable['ref'], guide['path'])}): {guide['summary']}")
    lines += ["", f"## {catalog['next']['label']}", ""]
    for guide in catalog["guides"]:
        lines.append(f"- [{guide['title']}]({guide['path']}): {guide['summary']}")
    lines += ["", "## Public products", ""]
    for product in catalog["products"]:
        lines.append(f"- `{product['name']}` ({product['kind']}): [{product['docs']}]({product['docs']})")
    return "\n".join(lines) + "\n"


def navigation(catalog: dict) -> str:
    stable = catalog["stable"]
    lines = [
        "<!-- Generated by Scripts/generate-doc-navigation.py; edit docs/catalog.json. -->",
        "# Documentation navigation",
        "",
        f"Stable [{stable['version']}](stable/{stable['version']}/) is the default immutable channel. [{catalog['next']['label']}](next/) follows `main` and is unreleased.",
        "",
        "| Guide | Purpose |",
        "| --- | --- |",
    ]
    def relative(path: str) -> str:
        return path.removeprefix("docs/") if path.startswith("docs/") else f"../{path}"

    for guide in catalog["guides"]:
        lines.append(f"| [{guide['title']}]({relative(guide['path'])}) | {guide['summary']} |")
    lines += ["", "## Public products", "", "| Product | Kind | Consumer gate | Documentation |", "| --- | --- | --- | --- |"]
    for product in catalog["products"]:
        lines.append(f"| `{product['name']}` | {product['kind']} | `{product['consumer']}` | [{product['docs']}]({relative(product['docs'])}) |")
    return "\n".join(lines) + "\n"


def outputs(catalog: dict) -> dict[Path, str]:
    return {
        ROOT / "docs/index.html": landing(catalog, channel="stable", switch_href="next/"),
        ROOT / "docs/stable/index.html": landing(catalog, channel="stable", switch_href="../next/"),
        ROOT / "docs/next/index.html": landing(catalog, channel="next", switch_href="../"),
        ROOT / "docs/NAVIGATION.md": navigation(catalog),
        ROOT / "llms.txt": llms(catalog),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    stale: list[str] = []
    for path, expected in outputs(load_catalog()).items():
        if args.check:
            actual = path.read_text(encoding="utf-8") if path.exists() else ""
            if actual != expected:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
    if stale:
        print("Generated documentation is stale:", file=sys.stderr)
        for path in stale:
            print(f"  {path}", file=sys.stderr)
        print("Run: python3 Scripts/generate-doc-navigation.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
