#!/usr/bin/env python3
"""Generate bindable, type-checkable Swift sources from docs fenced code blocks.

Reads every ```swift fence under a docs tree and writes one generated Swift file
per block into <out_dir>/Generated, plus a shared prelude that binds the
placeholder identifiers the guides use (`kit`, `myLanguageModel`,
`myRuntimeRepository`, ...). The shell gate then builds the DocSnippetConsumer
target so a stale label, arity, or type in a guide fails the build.

A fence may opt out of type-checking with the greppable marker:

    ```swift skip

Skipped blocks are written verbatim into <parse_dir> for the cheap
`swiftc -parse` pass; <parse_dir> must stay outside the SwiftPM target path so
`swift build` never compiles raw snippets. Everything else is wrapped so its
top-level statements can live in a library target.

The generator is deterministic: it rewrites a file only when its content
changed, so an unchanged tree rebuilds incrementally.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Modules the generated wrappers and prelude may name. Importing a module a
# block does not use is harmless; the point is that a block never depends on a
# transitive import.
DEFAULT_IMPORTS = [
    "import Foundation",
    "import JSONSchemaBuilder",
    "import Logging",
    "import PKContracts",
    "import PKOpenAIProvider",
    "import PKOllamaProvider",
    "import PKAnthropicProvider",
    "import PKPrompt",
    "import PKTestSupport",
    "import PositronicKit",
]

# Placeholder identifier -> the concrete public type the guides intend. The
# prelude binds each one from a `fatalError()` stub, so the snippet's API calls
# are type-checked against the real modules even though the value never exists.
PLACEHOLDERS = [
    ("kit", "PKRuntime"),
    ("chat", "PKRuntime"),
    ("timeline", "TimelineHandle"),
    ("timelineID", "UUID"),
    ("agent", "Agent"),
    ("myLLM", "any LLMStreamClient"),
    ("myLanguageModel", "any LLMStreamClient"),
    ("streamClient", "any LLMStreamClient"),
    ("myRuntimeRepository", "any TimelineRuntimeRepository"),
    ("myTimelineRuntimeRepository", "any TimelineRuntimeRepository"),
    ("myWorkspacePersistence", "any WorkspaceStore"),
    ("myWorkspaceStore", "any WorkspaceStore"),
    ("myToolPersistence", "any ToolPersistenceProtocol"),
    ("myToolStore", "any ToolPersistenceProtocol"),
    ("myAgentStore", "any AgentStoreProtocol"),
    ("myRequestOriginStore", "any RequestOriginStoreProtocol"),
    ("myWorkspaceBindingRepository", "any WorkspaceBindingRepository"),
    ("myWorkspaceCreator", "any WorkspaceFactory"),
    ("myRuntimeCustomization", "RuntimeCustomization"),
    ("myWorkspaceRoot", "URL"),
    ("tools", "[any PKTool]"),
    ("title", "SidecarDirective"),
    ("tone", "SidecarDirective"),
]

# Placeholder callbacks the guides pass around as if the reader defined them.
PLACEHOLDER_CALLBACKS = [
    ("render", "(String) -> Void", "{ _ in }"),
    ("enableGeneration", "() -> Void", "{}"),
    ("show", "(ModelReadinessReason) -> Void", "{ _ in }"),
]

FENCE_OPEN = re.compile(r"^```swift\b(.*)$")
FENCE_CLOSE = re.compile(r"^```\s*$")
TOP_LEVEL_DECL = re.compile(r"^(?:let|var)\s+([A-Za-z_][A-Za-z0-9_]*)")
SKIP_TOKEN = re.compile(r"\b(skip|no-typecheck)\b")

PRELUDE_HEADER = """\
// Generated by Scripts/compile-doc-snippets.sh. Do not edit.
// Shared bindable stubs so guide snippets that use placeholder identifiers can
// still be type-checked against the real modules.
"""


def render_prelude() -> str:
    lines = PRELUDE_HEADER.splitlines()
    lines.append("")
    lines.extend(DEFAULT_IMPORTS)
    lines.append("")
    lines.append("internal enum DocSnippetPrelude {")
    for name, type_name in PLACEHOLDERS:
        lines.append(f"    static func {name}() -> {type_name} {{")
        lines.append(f'        fatalError("docs placeholder: {name}")')
        lines.append("    }")
    for name, type_name, body in PLACEHOLDER_CALLBACKS:
        lines.append(f"    static func {name}() -> {type_name} {{ {body} }}")
    lines.append("}")
    lines.append("")
    lines.append("// The conformance-suite guide expects the reader to supply a WorkspaceStore;")
    lines.append("// the shipped test double stands in for it.")
    lines.append("internal typealias MyWorkspaceStore = MockWorkspacePersistence")
    lines.append("")
    return "\n".join(lines)


def collect_imports(body: str) -> tuple[list[str], str]:
    """Hoist `import` lines out of a block body; functions cannot contain them."""
    imports: list[str] = []
    kept: list[str] = []
    for line in body.splitlines():
        if re.match(r"^\s*(?:@_exported\s+|internal\s+|public\s+)?import\s", line):
            stripped = line.strip()
            if stripped not in imports:
                imports.append(stripped)
        else:
            kept.append(line)
    return imports, "\n".join(kept)


def declared_names(body: str) -> list[str]:
    """Column-zero `let`/`var` bindings a wrapper must mark as consumed."""
    names: list[str] = []
    for line in body.splitlines():
        match = TOP_LEVEL_DECL.match(line)
        if match and match.group(1) not in names:
            names.append(match.group(1))
    return names


def split_attached_declarations(body: str) -> tuple[str, str]:
    """Separate macro-attached declarations from wrapped statements.

    A `@Schemable` type or `@Test` function cannot be nested in another function
    (`local type cannot have attached extension macro` / `Attribute 'Test' cannot
    be applied to a function within a function`), so those declarations stay at
    file scope while the block's executable statements are wrapped.
    """
    lines = body.splitlines()
    declarations: list[str] = []
    statements: list[str] = []
    index = 0
    while index < len(lines):
        line = lines[index]
        if not (line.startswith("@") and re.match(r"@[A-Za-z_]", line)):
            statements.append(line)
            index += 1
            continue
        segment = [line]
        depth = line.count("{") - line.count("}")
        opened = "{" in line
        cursor = index + 1
        while (not opened or depth > 0) and cursor < len(lines):
            following = lines[cursor]
            segment.append(following)
            depth += following.count("{") - following.count("}")
            if "{" in following:
                opened = True
            cursor += 1
        declarations.append("\n".join(segment))
        index = cursor
    return "\n".join(declarations), "\n".join(statements)


def render_block(
    source_label: str,
    declarations: str,
    statements: str,
    imports: list[str],
) -> str:
    lines = [f"// {source_label}"]
    ordered = list(dict.fromkeys(imports + DEFAULT_IMPORTS))
    lines.extend(ordered)
    lines.append("")
    if declarations:
        lines.append(declarations)
        lines.append("")
    if statements.strip():
        lines.append(f"internal enum {source_label_identifier(source_label)} {{")
        lines.append("    static func run() async throws {")
        for name, _ in PLACEHOLDERS:
            lines.append(f"        let {name} = DocSnippetPrelude.{name}()")
            lines.append(f"        _ = {name}")
        for name, _, _ in PLACEHOLDER_CALLBACKS:
            lines.append(f"        let {name} = DocSnippetPrelude.{name}()")
            lines.append(f"        _ = {name}")
        lines.append("        do {")
        lines.append(statements)
        for name in declared_names(statements):
            lines.append(f"        _ = {name}")
        lines.append("        }")
        lines.append("    }")
        lines.append("}")
    lines.append("")
    return "\n".join(lines)


def source_label_identifier(label: str) -> str:
    return "DocSnippet_" + re.sub(r"[^A-Za-z0-9]", "_", label)


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.write_text(content, encoding="utf-8")
    return True


def parse_blocks(text: str) -> list[tuple[str, str]]:
    lines = text.splitlines()
    blocks: list[tuple[str, str]] = []
    index = 0
    while index < len(lines):
        opening = FENCE_OPEN.match(lines[index])
        if not opening:
            index += 1
            continue
        info = opening.group(1).strip()
        cursor = index + 1
        while cursor < len(lines) and not FENCE_CLOSE.match(lines[cursor]):
            cursor += 1
        blocks.append((info, "\n".join(lines[index + 1 : cursor])))
        index = cursor + 1
    return blocks


def generate(docs_dir: Path, out_dir: Path, parse_dir: Path) -> tuple[int, int]:
    generated_dir = out_dir / "Generated"
    generated_dir.mkdir(parents=True, exist_ok=True)
    parse_dir.mkdir(parents=True, exist_ok=True)

    expected_generated: set[Path] = {generated_dir / "Prelude.swift"}
    expected_parse: set[Path] = set()
    checked = 0
    skipped = 0

    markdown_files = sorted(docs_dir.rglob("*.md"))
    for markdown in markdown_files:
        base = markdown.stem
        for number, (info, body) in enumerate(parse_blocks(markdown.read_text(encoding="utf-8")), start=1):
            label = f"docs/{markdown.relative_to(docs_dir).as_posix()} block {number}"
            name = f"{base}.{number}.swift"
            if SKIP_TOKEN.search(info):
                skipped += 1
                target = parse_dir / name
                expected_parse.add(target)
                write_if_changed(target, body)
                continue
            imports, stripped = collect_imports(body)
            declarations, statements = split_attached_declarations(stripped)
            content = render_block(label, declarations, statements, imports)
            checked += 1
            target = generated_dir / name
            expected_generated.add(target)
            write_if_changed(target, content)

    if checked:
        write_if_changed(generated_dir / "Prelude.swift", render_prelude())
    else:
        expected_generated.discard(generated_dir / "Prelude.swift")

    for directory, expected in (
        (generated_dir, expected_generated),
        (parse_dir, expected_parse),
    ):
        for stale in directory.glob("*.swift"):
            if stale not in expected:
                stale.unlink()

    return checked, skipped


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("docs_dir", type=Path)
    parser.add_argument("out_dir", type=Path)
    parser.add_argument(
        "parse_dir",
        type=Path,
        help="outside the SwiftPM target path; skipped blocks are only parse-checked",
    )
    args = parser.parse_args()

    if not args.docs_dir.is_dir():
        print(f"generate-doc-snippets: {args.docs_dir} is not a directory", file=sys.stderr)
        return 2
    checked, skipped = generate(args.docs_dir, args.out_dir, args.parse_dir)
    print(f"generate-doc-snippets: {checked} type-checked, {skipped} parse-only")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
